export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const SAVE_THEME = 'SAVE_THEME';
export const GET_SETTINGS = 'GET_SETTINGS';
export const FETCH_PENDING = 'FETCH_PENDING';
export const FETCH_DONE = 'FETCH_DONE';
